#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

get_variables() {
  [ "${ROOT_MOUNT}" = "false" ] && return 1
  local response="x"
  local debug_archive="${ROOT_MOUNT}/CONFIG/imgldr_debug.tar"
  local debug_dir="${ROOT_MOUNT}/CONFIG/imgldr_debug"
  if [ -f "$debug_archive" ] || ls "$debug_dir/"* >/dev/null 2>&1; then
    imgldr_pretty_text "      !!! DEBUG MODE !!!" "   Debug scripts are loaded."
    DEBUG_MODE="true"
    mkdir -p /lib/imgldr
    if [ -f "$debug_archive" ]; then
      tar -xf "$debug_archive" -C /lib/imgldr >/dev/null 2>&1 || echo "... WARNING: IMGLDR FAILED TO EXTRACT DEBUG SCRIPTS ARCHIVE ..."
    elif ls "$debug_dir/"* >/dev/null 2>&1; then
      ls "$debug_dir/"* >/dev/null 2>&1 && cp -rf "$debug_dir/"* /lib/imgldr/ >/dev/null 2>&1
    fi
    chown -R 0:0 /lib/imgldr
    chmod -R +x /lib/imgldr
  fi
  if [ "${SQFS_MOUNT}" = "false" ] && [ -f "${ROOT_MOUNT}/sbin/init" ]; then
    imgldr_pretty_text "       !!! WARNING !!!" "    system.sqfs not found!" "  running local installation" "          instead..."
    BOOT="local"
    if [ "${DEBUG_MODE}" = "true" ]; then
      echo " "
      echo "DEBUGMODE option: What would you do?"
      echo "continue local? (ENTER), force imgldr boot? (i), enter console? (c), reboot? (r), poweroff? (p)"
      while [ "${response}" != "" ] && [ "${response}" != "i" ] && [ "${response}" != "c" ] && 
            [ "${response}" != "r" ] && [ "${response}" != "p" ]; do
        read -n 1 -s response
      done
      if [ "$response" = "i" ]; then
        BOOT="imgldr"
      fi
      if [ "$response" = "c" ]; then
        imgldr_shell_console
      fi
      if [ "$response" = "r" ]; then
        imgldr_do_reboot
      fi
      if [ "$response" = "p" ]; then
        imgldr_do_poweroff
      fi
    fi
  elif [ "${SQFS_MOUNT}" = "false" ]; then
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "    system.sqfs not found!" "local installation not found!" "     nothing to boot up!"
  fi
  mkdir -p /conf
  touch /conf/param.conf
  echo "BOOT=$BOOT" >> "/conf/param.conf"
  echo "DEBUG_MODE=$DEBUG_MODE" >> "/conf/param.conf"
}

extract_imgldr_scripts() {
  [ "${ROOT_MOUNT}" = "false" ] && return 0
  [ "${SQFS_MOUNT}" = "false" ] && return 0
  [ "${BOOT}" != "imgldr" ] && return 0
  [ "${DEBUG_MODE}" = "true" ] && return 0
  local scripts_archive="${SQFS_MOUNT}/INFO/scripts.tar"
  if [ -f "$scripts_archive" ]; then
    mkdir -p /lib/imgldr
    tar -xf "$scripts_archive" -C /lib/imgldr >/dev/null 2>&1
    if [ $? -ne 0 ]; then
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "      Failed to extract" "       imgldr scripts." " Corrupted system.sqfs image!"
    fi
    chown -R 0:0 /lib/imgldr
    chmod -R +x /lib/imgldr
  else
    imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "Failed to find imgldr scripts." " Corrupted system.sqfs image!"
  fi
}

run_imgldr_premount() {
  [ "${BOOT}" != "imgldr" ] && return 0
  local premount_script="/lib/imgldr/premount"
  if [ -f "$premount_script" ]; then
    /bin/sh -c "$premount_script"
    if [ $? -ne 0 ]; then
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "imgldr premount script failed!"
    fi
    imgldr_reload_vars
  fi
}

DEBUG_MODE="false"
BOOT="imgldr"

# Load imgldr functions
if [ -f /scripts/imgldr_functions ]; then
  . /scripts/imgldr_functions
else
  echo "... ERROR: IMGLDR FAILED TO LOAD FUNCTIONS ..."
  if command -v setsid >/dev/null 2>&1; then
    read -r console rest </proc/consoles
    if [ "${console}" = "tty0" ]; then
      console="tty1"
    fi
    setsid sh -c "exec sh -i <>/dev/${console} 1>&0 2>&1"
  else
    sh -i </dev/console >/dev/console 2>&1
  fi
  echo "Rebooting in 5 seconds..."
  sleep 5
  reboot -f
fi

imgldr_mount_fs
get_variables
[ -f "${ROOT_MOUNT}/IMAGES/update_tmp" ] && . "${ROOT_MOUNT}/IMAGES/update_tmp"
extract_imgldr_scripts
run_imgldr_premount
imgldr_umount_fs

exit 0
