#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

export ROOT_CMDLINE="___ROOT_CMDLINE___"
export ROOT_DEV="___ROOT_DEV___"
export ROOT_MOUNT="false"
export SQFS_MOUNT="false"

wait_for_udev() {
  command -v udevadm >/dev/null 2>&1 || return 0
  udevadm settle ${1:+--timeout=$1}
}

get_cmdline() {
  for x in $(cat /proc/cmdline)
  do
    case $x in
      root=*)
        ROOT_CMDLINE=${x#root=}
      ;;
    esac
  done
}

pretty_text() {
  printf '%s\n%s  %-30s  %s\n' "######################################" "##" "" "##"
  for i in "${@}"; do
    printf "%s  %-30s  %s\n" "##" "$i" "##"
  done
  printf '%s  %-30s  %s\n%s\n' "##" "" "##" "######################################"
}

shell_console() {
  if command -v setsid >/dev/null 2>&1; then
    read -r console rest </proc/consoles
    if [ "${console}" = "tty0" ]; then
      console="tty1"
    fi
    setsid sh -c "exec sh -i <>/dev/${console} 1>&0 2>&1"
  else
    sh -i </dev/console >/dev/console 2>&1
  fi
}

panic_pretty() {
  [ $# -ne 0 ] && pretty_text "${@}"
  local response="x"
  echo " "
  echo "What would you do?"
  echo "enter console? (c), reboot? (r), poweroff? (p)"
  while [ "${response}" != "c" ] && [ "${response}" != "r" ] && [ "${response}" != "p" ]; do
    read -n 1 -s response
  done
  if [ "$response" = "c" ]; then
    shell_console
  fi
  if [ "$response" = "r" ]; then
    echo "Reboot in 5 seconds..."
    sleep 5
    reboot -f
  fi
  if [ "$response" = "p" ]; then
    echo "Power off in 5 seconds..."
    sleep 5
    poweroff -f
  fi
}

get_devices() {
  if [ "$ROOT_CMDLINE" = "___ROOT_CMDLINE___" ]; then
    panic_pretty "     !!! KERNEL PANIC !!!" "  No root device specified." " Boot arguments must include" "      a root= parameter."
  fi
  wait_for_udev 10
  n=0
  while [ "$n" -lt 10 ]; do
    case "$ROOT_CMDLINE" in
      LABEL=* | UUID=* | PARTLABEL=* | PARTUUID=*)
        ROOT_DEV="$(blkid -l -t "$ROOT_CMDLINE" -o device)" || ROOT_DEV="___ROOT_DEV___"
      ;;
    esac
    n=$((n+1))
    sleep 1.0
  done
}

mount_fs() {
  if [ "$ROOT_DEV" != "___ROOT_DEV___" ]; then
    mkdir -p /mnt/tmproot
    if mount -w "$ROOT_DEV" /mnt/tmproot; then
      ROOT_MOUNT="/mnt/tmproot"
    else
      panic_pretty "     !!! KERNEL PANIC !!!" " Failed to mount root device." "Check if the device exists and" " is a valid root filesystem." "${ROOT_DEV}"
    fi
    if [ -f "/mnt/tmproot/IMAGES/system.sqfs" ]; then
      mkdir -p /mnt/syssqfs
      if mount -t squashfs /mnt/tmproot/IMAGES/system.sqfs /mnt/syssqfs; then
        SQFS_MOUNT="/mnt/syssqfs"
      else
        echo "... WARNING: IMGLDR FAILED TO MOUNT SQUASHFS IMAGE ..."
      fi
    fi
  else
    panic_pretty "     !!! KERNEL PANIC !!!" " Failed to find root device." "Check if the device exists and" " is a valid root filesystem." "${ROOT_DEV}"
  fi
}

umount_fs() {
  local attempt=1
  sync >/dev/null 2>&1
  while [ "$SQFS_MOUNT" != "false" ] && [ $attempt -le 30 ]; do
    umount /mnt/syssqfs >/dev/null 2>&1 && SQFS_MOUNT="false" || { sleep 1; attempt=$((attempt + 1)); }
  done
  attempt=1
  while [ "$ROOT_MOUNT" != "false" ] && [ $attempt -le 30 ]; do
    umount /mnt/tmproot >/dev/null 2>&1 && ROOT_MOUNT="false" || { sleep 1; attempt=$((attempt + 1)); }
  done
  [ "$SQFS_MOUNT" != "false" ] && echo "Could not umount: /mnt/syssqfs"
  [ "$ROOT_MOUNT" != "false" ] && echo "Could not umount: /mnt/tmproot"
}

get_variables() {
  [ "$ROOT_MOUNT" = "false" ] && return 0
  if [ "$SQFS_MOUNT" != "false" ]; then
    BOOT="imgldr"
  else
    if [ -f "/mnt/tmproot/sbin/init" ]; then
      pretty_text "       !!! WARNING !!!" "    system.sqfs not found!" "  running local installation" "          instead..."
      BOOT="local"
    else
      panic_pretty "     !!! KERNEL PANIC !!!" "    system.sqfs not found!" "local installation not found!" "     nothing to boot up!" "${ROOT_DEV}"
    fi
  fi
}

extract_imgldr_scripts() {
  [ "$SQFS_MOUNT" = "false" ] && return 0
  local scripts_archive="/mnt/syssqfs/INFO/scripts.tar"
  if [ -f "$scripts_archive" ]; then
    mkdir -p /usr/share/imgldr
    tar -xf "$scripts_archive" -C /usr/share/imgldr >/dev/null 2>&1 || echo "... WARNING: IMGLDR FAILED TO EXTRACT SCRIPTS ARCHIVE ..."
    chown -R 0:0 /usr/share/imgldr
    chmod -R +x /usr/share/imgldr
  else
    echo "... WARNING: IMGLDR SCRIPTS ARCHIVE NOT FOUND ..."
  fi
}

run_imgldr_premount() {
  [ "$SQFS_MOUNT" = "false" ] && return 0
  local premount_script="/usr/share/imgldr/premount"
  if [ -f "$premount_script" ]; then
    /bin/sh -c "$premount_script"
    if [ $? -ne 0 ]; then
      echo "... WARNING: IMGLDR PREMOUNT SCRIPT FAILED ..."
    fi
  fi
}

export_variables() {
  mkdir -p /conf
  touch /conf/param.conf
  echo "BOOT=$BOOT" >> "/conf/param.conf"
}

get_cmdline
get_devices
mount_fs
get_variables
extract_imgldr_scripts
run_imgldr_premount
umount_fs
export_variables

exit 0
