#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ -f /scripts/imgldr_functions ]; then
  . /scripts/imgldr_functions
else
  echo "... ERROR: IMGLDR FAILED TO LOAD FUNCTIONS ..."
  if command -v setsid >/dev/null 2>&1; then
    read -r console rest </proc/consoles
    if [ "${console}" = "tty0" ]; then
      console="tty1"
    fi
    setsid sh -c "exec sh -i <>/dev/${console} 1>&0 2>&1"
  else
    sh -i </dev/console >/dev/console 2>&1
  fi
fi

get_variables() {
  [ "${ROOT_MOUNT}" = "false" ] && return 0
  if [ "${SQFS_MOUNT}" != "false" ]; then
    BOOT="imgldr"
  else
    if [ -f "${ROOT_MOUNT}/sbin/init" ]; then
      imgldr_pretty_text "       !!! WARNING !!!" "    system.sqfs not found!" "  running local installation" "          instead..."
      BOOT="local"
    else
      imgldr_panic_pretty "     !!! KERNEL PANIC !!!" "    system.sqfs not found!" "local installation not found!" "     nothing to boot up!" "${ROOT_DEV}"
    fi
  fi
}

extract_imgldr_scripts() {
  [ "${SQFS_MOUNT}" = "false" ] && return 0
  local scripts_archive="${SQFS_MOUNT}/INFO/scripts.tar"
  if [ -f "$scripts_archive" ]; then
    mkdir -p /usr/share/imgldr
    tar -xf "$scripts_archive" -C /usr/share/imgldr >/dev/null 2>&1 || echo "... WARNING: IMGLDR FAILED TO EXTRACT SCRIPTS ARCHIVE ..."
    chown -R 0:0 /usr/share/imgldr
    chmod -R +x /usr/share/imgldr
  else
    echo "... WARNING: IMGLDR SCRIPTS ARCHIVE NOT FOUND ..."
  fi
}

run_imgldr_premount() {
  [ "${SQFS_MOUNT}" = "false" ] && return 0
  local premount_script="/usr/share/imgldr/premount"
  if [ -f "$premount_script" ]; then
    /bin/sh -c "$premount_script"
    if [ $? -ne 0 ]; then
      echo "... WARNING: IMGLDR PREMOUNT SCRIPT FAILED ..."
    fi
  fi
}

export_variables() {
  mkdir -p /conf
  touch /conf/param.conf
  echo "BOOT=$BOOT" >> "/conf/param.conf"
}

imgldr_mount_fs
get_variables
extract_imgldr_scripts
run_imgldr_premount
imgldr_umount_fs
export_variables

exit 0
